from .ApprovalPage import ApprovalPage
from .DashboardPage import DashboardPage
#from .CredentialsPage import CredentialsPage
from .DeskewPage import DeskewPage
from .DiscoveryPage import DiscoveryPage
#from .EmptyPage import EmptyPage
from .MainWindow import MainWindow
from .MetadataPage import MetadataPage
#from .SchemaBuilderPage import SchemaBuilderPage
from .UploadPage import UploadPage
from .SingleDocumentPage import SingleDocumentPage
from .StepDashboardPage import StepDashboardPage