from .Dashboard import DashboardPage
from .MainWindow import MainWindow
from .MetadataPage import MetadataPage
from .UploadPage import UploadPage
from .DocumentReviewPage import DocumentReviewPage
from .CreateDocumentPage import CreateDocumentPage
from .SettingsPage import SettingsPage
from .ReviewDashboard import ReviewPage
from .HelpPage import HelpPage
